// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-locale';
export { Provider, useModel } from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-access/types.d';
export * from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-antd/types.d';
export * from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-layout/types.d';
export * from 'D:/workspaces/wingman/dashboard/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@umijs+renderer-react@4.5.3_ea331d0589dc8c9b1879a3919ebd4dcd/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@umijs+renderer-react@4.5.3_ea331d0589dc8c9b1879a3919ebd4dcd/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/umi@4.5.3_@babel+core@7.28._95d676c88582dfe26fcb1efe8d7b2f33/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
