from __future__ import annotations

from typing import TypedDict

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。
# setFiles 接受变参：每个实参为路径字符串或路径列表（两种形态可混用）。


class ClipboardImage(TypedDict):
    """getImage() 返回的剪贴板图像（data 为图像字节串，无图像时返回 None）。"""

    data: str
    width: int
    height: int


def setText(text: str) -> bool: ...
def set_text(text: str) -> bool: ...
def getText() -> str: ...
def get_text() -> str: ...
def hasText() -> bool: ...
def has_text() -> bool: ...
def setHTML(html: str) -> bool: ...
def set_html(html: str) -> bool: ...
def getHTML() -> str: ...
def get_html() -> str: ...
def hasHTML() -> bool: ...
def has_html() -> bool: ...
def setImage(imageData: str, width: int, height: int) -> bool: ...
def set_image(imageData: str, width: int, height: int) -> bool: ...
def getImage() -> ClipboardImage | None: ...
def get_image() -> ClipboardImage | None: ...
def hasImage() -> bool: ...
def has_image() -> bool: ...
def setFiles(*files: str | list[str]) -> bool: ...
def set_files(*files: str | list[str]) -> bool: ...
def getFiles() -> list[str]: ...
def get_files() -> list[str]: ...
def hasFiles() -> bool: ...
def has_files() -> bool: ...
def clear() -> None: ...
def isEmpty() -> bool: ...
def is_empty() -> bool: ...
