from __future__ import annotations

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。
# 失败/缺参时返回空字符串（不抛异常）。sha256/sha512 无大写字母，无别名。

def encryptAES(plaintext: str, password: str, salt: str = ...) -> str: ...
def encrypt_aes(plaintext: str, password: str, salt: str = ...) -> str: ...
def decryptAES(ciphertext: str, password: str) -> str: ...
def decrypt_aes(ciphertext: str, password: str) -> str: ...
def deriveKey(password: str, salt: str, iterations: int = ..., keyLen: int = ...) -> str: ...
def derive_key(password: str, salt: str, iterations: int = ..., keyLen: int = ...) -> str: ...
def generateSalt(length: int = ...) -> str: ...
def generate_salt(length: int = ...) -> str: ...
def sha256(data: str) -> str: ...
def sha512(data: str) -> str: ...
def base64Encode(data: str) -> str: ...
def base64_encode(data: str) -> str: ...
def base64Decode(data: str) -> str: ...
def base64_decode(data: str) -> str: ...
def hexEncode(data: str) -> str: ...
def hex_encode(data: str) -> str: ...
def hexDecode(data: str) -> str: ...
def hex_decode(data: str) -> str: ...
def randomBytes(length: int = ...) -> str: ...
def random_bytes(length: int = ...) -> str: ...
