from __future__ import annotations

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。
# IO 基于 std::filesystem 实现，系统调用异常吞掉转为 None/False，不向脚本抛出。

def read(path: str) -> str | None: ...
def write(path: str, content: str) -> bool: ...
def append(path: str, content: str) -> bool: ...
def exists(path: str) -> bool: ...
def isFile(path: str) -> bool: ...
def is_file(path: str) -> bool: ...
def isDir(path: str) -> bool: ...
def is_dir(path: str) -> bool: ...
def size(path: str) -> int | None: ...
def move(src: str, dst: str) -> bool: ...
def copy(src: str, dst: str) -> bool: ...
def remove(path: str) -> bool: ...
def removeAll(path: str) -> bool: ...
def remove_all(path: str) -> bool: ...
def mkdir(path: str) -> bool: ...
def listDir(path: str) -> list[str] | None: ...
def list_dir(path: str) -> list[str] | None: ...
