from __future__ import annotations

from typing import Any, Callable

WatchCallback = Callable[..., Any]

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。

# 回调载荷：{"type": "added"|"removed"|"modified"|"renamed_old"|"renamed_new",
#            "path": str, "oldPath": str, "timestamp": int}
# 返回注册 ID（0 = 失败：回调非线程安全或原生后端注册失败）。
def watch(path: str, callback: WatchCallback, recursive: bool = True) -> int: ...
def unwatch(path: str) -> bool: ...
def unwatchAll() -> None: ...
def unwatch_all() -> None: ...
def isWatching(path: str) -> bool: ...
def is_watching(path: str) -> bool: ...
def getWatchedPaths() -> list[str]: ...
def get_watched_paths() -> list[str]: ...
