from __future__ import annotations

from typing import Any, Callable

WatchCallback = Callable[..., Any]

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。

def watch(path: str, callback: WatchCallback) -> bool: ...
def unwatch(path: str) -> bool: ...
def unwatchAll() -> None: ...
def unwatch_all() -> None: ...
def isWatching(path: str) -> bool: ...
def is_watching(path: str) -> bool: ...
def getWatchedPaths() -> list[str]: ...
def get_watched_paths() -> list[str]: ...
