from __future__ import annotations

from typing import Any, Callable, TypedDict

class TransitionSpec(TypedDict, total=False):
    on: str
    guard: Callable[[dict[str, Any]], bool]
    action: Callable[[dict[str, Any]], None]

class StateMachine:
    def state(self, name: str, on_enter: Callable[[dict[str, Any]], None] | None = ..., on_exit: Callable[[dict[str, Any]], None] | None = ...) -> "StateMachine": ...
    def transition(self, source: str, target: str, on: str | None = ..., guard: Callable[[dict[str, Any]], bool] | None = ..., action: Callable[[dict[str, Any]], None] | None = ...) -> "StateMachine": ...
    def dispatch(self, event: str, payload: dict[str, Any] | None = ...) -> bool: ...
    def current(self) -> str: ...
    def reset(self) -> None: ...

def create(name: str, initial: str, options: dict[str, Any] | None = ...) -> StateMachine: ...
