from __future__ import annotations

def load(id: str) -> bool: ...
def save(id: str) -> bool: ...
def get(id: str) -> tuple[str, str] | None: ...
def getActive() -> tuple[str, str] | None: ...
def setActive(id: str) -> bool: ...
def list() -> list[str]: ...
def findByWindow(title: str) -> tuple[str, str] | None: ...

