from __future__ import annotations

from .types import HttpOptions, HttpResponse

def get(url: str, options: HttpOptions | dict | None = ...) -> HttpResponse: ...
def post(url: str, body: str = ..., options: HttpOptions | dict | None = ...) -> HttpResponse: ...
def put(url: str, body: str = ..., options: HttpOptions | dict | None = ...) -> HttpResponse: ...
def delete(url: str, options: HttpOptions | dict | None = ...) -> HttpResponse: ...
