from __future__ import annotations

def mouse_move(x: int, y: int, duration: int = ...) -> None: ...
def mouse_click(x: int, y: int) -> None: ...
def mouse_rightClick(x: int, y: int) -> None: ...
def mouse_doubleClick(x: int, y: int) -> None: ...
def mouse_drag(fromX: int, fromY: int, toX: int, toY: int) -> None: ...
def mouse_scroll(x: int, y: int, delta: int = ...) -> None: ...
def keyboard_press(vkCode: int) -> None: ...
def keyboard_down(vkCode: int) -> None: ...
def keyboard_up(vkCode: int) -> None: ...
def keyboard_type(text: str, randomCase: bool = ...) -> None: ...

