from __future__ import annotations

from typing import Any

# 消息收件箱模块（与 Go orchestrator 的消息交互）。
# 注: 受 WINGMAN_HAS_TRANSPORT 编译选项保护，未启用时模块不可用。
# 函数签名以 C++ 实现 (lib/wingman/src/script/modules/inbox_module.cpp) 为准。

def connect(url: str, clientId: str = ..., *args: Any, **kwargs: Any) -> bool: ...
def consume(timeout: int = ...) -> list[dict]: ...
def ack(messageId: str) -> bool: ...
def report(status: dict | str, *args: Any, **kwargs: Any) -> bool: ...
def heartbeat(*args: Any, **kwargs: Any) -> bool: ...
def disconnect() -> bool: ...
def isConnected() -> bool: ...
