from __future__ import annotations

def click(x: int, y: int, button: int = ...) -> None: ...
def move(x: int, y: int, duration: int = ...) -> None: ...
def scroll(x: int, y: int, delta: int) -> None: ...
def keyDown(vkCode: int) -> None: ...
def keyUp(vkCode: int) -> None: ...
def key(vkCode: int) -> None: ...
def type(text: str, delay: int = ...) -> None: ...
def delay(ms: int) -> None: ...
def randomDelay(minMs: int, maxMs: int) -> None: ...

