from __future__ import annotations

def set(key: str, value: str, options: dict | None = ...) -> None: ...
def get(key: str) -> str: ...
def delete(key: str | list[str]) -> None: ...
def exists(key: str) -> bool: ...
def expire(key: str, seconds: int) -> None: ...
def ttl(key: str) -> int: ...
def incr(key: str, delta: int = ...) -> int: ...
def hset(hash: str, field: str, value: str) -> None: ...
def hget(hash: str, field: str) -> str: ...
def hgetall(hash: str) -> dict[str, str]: ...
def hdel(hash: str, field: str) -> None: ...
def lpush(list: str, value: str) -> None: ...
def rpush(list: str, value: str) -> None: ...
def lpop(list: str) -> str: ...
def rpop(list: str) -> str: ...
def llen(list: str) -> int: ...
def lrange(list: str, start: int, stop: int) -> list[str]: ...

