from __future__ import annotations

from typing import Any

def debug(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def info(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def warn(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def error(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def toast(title: str, message: str, level: str | None = ...) -> bool: ...
def webhook(url: str, payload: dict[str, Any], options: dict[str, Any] | None = ...) -> bool: ...
def bridge(eventPattern: str, target: str, options: dict[str, Any] | None = ...) -> bool: ...
