from __future__ import annotations

from typing import Any

# 除 tray* 外各函数均只发事件、立即返回 None（webhook 结果经
# notify.webhook.success/failed 事件回投）。trayShow/trayHide/traySetBadge/
# traySetTooltip 按注册名声明；引擎对 camelCase 注册名自动追加 snake_case
# 别名（camelToSnake），两种签名均可调用。bridge 仅匹配精确事件名，不支持通配。


def debug(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def info(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def warn(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def error(message: str, meta: dict[str, Any] | None = ...) -> None: ...
def toast(title: str, message: str, level: str | None = ...) -> None: ...
def webhook(url: str, payload: dict[str, Any] | None = ..., options: dict[str, Any] | None = ...) -> None: ...
def bridge(eventName: str, target: str, options: dict[str, Any] | None = ...) -> None: ...

# ===== 托盘（GUI 附属，runtime 发意图事件）=====

def trayShow() -> bool: ...
def tray_show() -> bool: ...
def trayHide() -> bool: ...
def tray_hide() -> bool: ...
def traySetBadge(text: str | None = ...) -> bool: ...
def tray_set_badge(text: str | None = ...) -> bool: ...
def traySetTooltip(text: str) -> bool: ...
def tray_set_tooltip(text: str) -> bool: ...
