from __future__ import annotations

def submit_workflow(workflow: dict) -> str | None: ...
def cancel_workflow(workflowId: str) -> bool: ...
def get_workflow(workflowId: str) -> dict | None: ...
def get_all_workflows() -> list[dict]: ...

