from __future__ import annotations

from .types import Point

def setConfig(config: dict) -> None: ...
def getConfig() -> dict: ...
def preloadImage(path: str) -> None: ...
def clearCache() -> None: ...
def getCacheSize() -> int: ...
def getCacheStats() -> dict: ...
def fastFindImage(path: str, x: int, y: int, w: int, h: int, threshold: float) -> Point | None: ...
def parallelFindColors(color: int, x: int, y: int, w: int, h: int, tolerance: int, maxCount: int = ...) -> list[Point]: ...
def getStats() -> dict: ...
def resetStats() -> None: ...

