from __future__ import annotations

def find(name: str) -> tuple[int | None, bool]: ...
def start(path: str, args: str = ..., workdir: str = ...) -> int: ...
def wait(pid: int, timeout: int = ...) -> bool: ...
def terminate(pid: int, force: bool = ...) -> bool: ...
def exists(pid: int) -> bool: ...
def waitFor(name: str, timeout: int = ...) -> bool: ...
