from __future__ import annotations

from .types import QRLoginResult

def get(qrUrl: str, statusUrl: str) -> str | None: ...
def login(qrUrl: str, statusUrl: str, pollInterval: int = ...) -> QRLoginResult: ...
def cancel() -> None: ...
def detect(region: dict) -> str | None: ...
