from __future__ import annotations

from .types import Color, Point, Rect

def capture(x: int = ..., y: int = ..., width: int = ..., height: int = ...) -> bool: ...
def captureRegion(region: Rect) -> bool: ...
def getPixel(x: int, y: int) -> Color: ...
def findColor(color: int | Color | dict, region: Rect | dict, tolerance: int = ...) -> tuple[Point | None, bool]: ...
def findColors(color: int | Color | dict, region: Rect | dict, tolerance: int = ..., maxCount: int = ...) -> list[Point]: ...
def getScreenWidth() -> int: ...
def getScreenHeight() -> int: ...
def findImage(imagePath: str, region: Rect | dict | None = ..., threshold: float = ...) -> tuple[Point | None, bool]: ...

