from __future__ import annotations

def getRandomDelay() -> int: ...
def getRandomOffset() -> tuple[float, float]: ...
def isDebuggerPresent() -> bool: ...
def isRunningInVM() -> bool: ...
def verifyIntegrity() -> bool: ...
def hashString(text: str) -> str: ...
def encryptString(text: str, key: str) -> str: ...
def decryptString(text: str, key: str) -> str: ...
def generateRandomString(length: int) -> str: ...
def filterSensitive(text: str) -> str: ...

