from __future__ import annotations

from typing import Any

# condition/action 为描述符 dict（键表见 misc_modules.cpp parseCondition/
# parseAction；condition: type/color/tolerance/threshold/region/text/template，
# action: type/position/x/y/key/keyCode/waitMs/delay/script/message，type 值
# 兼容 snake_case 与大写枚举名）。函数按引擎注册名（camelCase 原名）声明；
# 引擎同时自动注册 snake_case 别名，两种签名均可调用。

TriggerCondition = dict[str, Any]
TriggerAction = dict[str, Any]


def create(name: str) -> bool: ...
def start(name: str) -> bool: ...
def stop(name: str) -> bool: ...
def remove(name: str) -> None: ...
def addCondition(name: str, condition: TriggerCondition) -> bool: ...
def add_condition(name: str, condition: TriggerCondition) -> bool: ...
def addAction(name: str, action: TriggerAction) -> bool: ...
def add_action(name: str, action: TriggerAction) -> bool: ...
def setCheckInterval(name: str, ms: int) -> bool: ...
def set_check_interval(name: str, ms: int) -> bool: ...
def isRunning(name: str) -> bool: ...
def is_running(name: str) -> bool: ...
def getTriggerCount(name: str) -> int: ...
def get_trigger_count(name: str) -> int: ...
