from __future__ import annotations

def getCpuInfo() -> dict: ...
def getCpuUsage() -> int: ...
def getMemoryInfo() -> dict: ...
def getDiskInfo(drive: str = ...) -> dict | list[dict]: ...
def getGpuInfo() -> list[dict]: ...
def getOsInfo() -> dict: ...
def getNetworkAdapters() -> list[dict]: ...
def getDisplayInfo() -> list[dict]: ...
def getUptime() -> int: ...
def getDateTime() -> str: ...
def getTimeZone() -> str: ...
def getProcessCount() -> int: ...
def getThreadCount() -> int: ...
