from __future__ import annotations

from typing import Any, Callable

# 模块函数按引擎注册名（camelCase 原名）声明；引擎对每个注册名自动追加
# snake_case 别名（camelToSnake），两种签名均可调用。
# 统一系统事件源（进程/窗口两腿；文件变化由 wingman.filewatcher 提供）。
# 回调从 SystemWatcher 后台轮询线程触发，需传 Python 函数（线程安全
# callable；Lua callable 会被拒绝并以 id=0 返回）。命中事件同时以
# "systemwatch.process"/"systemwatch.window" 进 wingman.event（source
# "systemwatch"，亦从后台线程分发，event.on 订阅同受线程安全约束）。

WatchCallback = Callable[[dict[str, Any]], Any]


def processWatch(name: str, callback: WatchCallback) -> int: ...
def process_watch(name: str, callback: WatchCallback) -> int: ...
def windowWatch(title: str, callback: WatchCallback) -> int: ...
def window_watch(title: str, callback: WatchCallback) -> int: ...
def unwatch(id: int) -> bool: ...
def clearAll() -> None: ...
def clear_all() -> None: ...
def watchCount(kind: str | None = None) -> int: ...
def watch_count(kind: str | None = None) -> int: ...
