from __future__ import annotations

def register(username: str = ...) -> str | None: ...
def join(teamId: str) -> bool: ...
def leave() -> bool: ...
def send(action: str, data: object | None = ...) -> bool: ...
def poll() -> list[dict]: ...
def members() -> list[dict]: ...
def info() -> dict: ...

