from __future__ import annotations

from typing import Any

# TCP/UDP 网络通信模块。
# 注: 受 WINGMAN_HAS_TRANSPORT 编译选项保护，未启用时模块不可用。
# 函数签名以 C++ 实现 (lib/wingman/src/script/modules/transport_module.cpp) 为准。

def tcpConnect(host: str, port: int, timeout: int = ...) -> str: ...
def tcpSend(sessionId: str, data: str) -> bool: ...
def tcpDisconnect(sessionId: str) -> bool: ...
def tcpIsConnected(sessionId: str) -> bool: ...
def tcpListen(port: int, host: str = ...) -> str: ...
def tcpSendTo(sessionId: str, data: str) -> bool: ...
def tcpBroadcast(data: str) -> bool: ...
def tcpCloseSession(sessionId: str) -> bool: ...
def tcpGetSessions() -> list[str]: ...
def tcpStop(listenerId: str = ...) -> bool: ...
def udpSocket() -> str: ...
def udpBind(sockId: str, port: int, host: str = ...) -> bool: ...
def udpSendTo(sockId: str, data: str, host: str, port: int) -> bool: ...
def udpRecvFrom(sockId: str, timeout: int = ...) -> dict | None: ...
def udpClose(sockId: str) -> bool: ...
