from __future__ import annotations

def totp(secret: str, digits: int = ..., period: int = ...) -> str: ...
def steamGuard(secret: str) -> str: ...
def saveTOTP(account: str, secret: str, digits: int = ..., period: int = ...) -> bool: ...
def loadTOTP(account: str) -> str | None: ...
def listTOTP() -> list[str]: ...
def removeTOTP(account: str) -> bool: ...
def getRemaining(secret: str, period: int = ...) -> int: ...
def verify(account: str, code: str, window: int = ...) -> bool: ...

