from __future__ import annotations

from .types import Color, Point, Rect

def findColor(color: int | Color | dict, tolerance: int = ..., region: Rect | dict | None = ...) -> Point | None: ...
def findAllColors(color: int | Color | dict, tolerance: int = ..., region: Rect | dict | None = ...) -> list[Point]: ...
def hasColor(color: int | Color | dict, tolerance: int = ..., region: Rect | dict | None = ...) -> bool: ...
def getDominantColor(region: Rect | dict | None = ...) -> Color: ...
def findImage(templatePath: str, threshold: float = ..., region: Rect | dict | None = ...) -> dict: ...
