from __future__ import annotations

from .types import Rect

def find(title: str) -> tuple[int | None, bool]: ...
def activate(handle: int) -> bool: ...
def getForeground() -> int: ...
def getTitle(handle: int) -> str: ...
def getBounds(handle: int) -> Rect: ...
def waitFor(title: str, timeout: int = ...) -> bool: ...
