import React, { useState, useEffect } from 'react';
import {
  Card,
  Button,
  Space,
  Row,
  Col,
  Alert,
  Switch,
  Tag,
  Spin,
  Empty,
  Divider,
  App,
  Select,
  Popconfirm,
  Typography,
} from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import { history, useModel } from '@umijs/max';
import {
  fetchFunctionUiHistory,
  listDescriptors,
  rollbackFunctionUiSchema,
  saveFunctionUiSchema,
} from '@/services/api/functions';
import SchemaRenderer from '@/components/formily/SchemaRenderer';
import UISchemaEditor from '@/components/UISchemaEditor';
import { FunctionFormRenderer, type JSONSchema } from '@/components/FunctionFormRenderer';
import { featureFlags } from '@/config/featureFlags';
import { fetchOptions } from '@/services/schema/async';
import { fetchFunctionUISchemaDocument } from '@/services/schema';
import { validateUiSchema } from '@/services/schema/validateSchema';
import { buildUISchemaFromJSONSchema } from '@/utils/json';

interface FunctionUIManagerProps {
  functionId: string;
  jsonSchema?: JSONSchema;
  descriptor?: any;
  onSave?: (uiSchema: any) => Promise<void>;
}

/**
 * 函数 UI 管理组件
 *
 * 功能：
 * 1. 预览 - 使用 FunctionFormRenderer 实时预览 UI 效果
 * 2. 编辑 - 使用 UISchemaEditor 编辑 UI Schema
 * 3. 启用 - 切换使用默认 UI 或自定义 UI
 */
export default function FunctionUIManager({
  functionId,
  jsonSchema,
  descriptor,
  onSave,
}: FunctionUIManagerProps) {
  const { Text } = Typography;
  const { message } = App.useApp();
  const { initialState } = useModel('@@initialState');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [uiConfig, setUiConfig] = useState<{
    schema?: any;
    layout?: any;
    components?: any;
  }>({});
  const [useCustomUI, setUseCustomUI] = useState(false);
  const [hasDefaultUI, setHasDefaultUI] = useState(false);
  const [uiSource, setUISource] = useState<string>('none');
  const [uiSourceDetail, setUISourceDetail] = useState<string>('');
  const [updatedAt, setUpdatedAt] = useState<string>('');
  const [originalSchema, setOriginalSchema] = useState<any>(undefined);
  const [isDirty, setIsDirty] = useState(false);
  const [historyItems, setHistoryItems] = useState<
    { version: number; createdAt?: string; createdBy?: string; message?: string }[]
  >([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [rollbackVersion, setRollbackVersion] = useState<number | undefined>();
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [relatedFunctions, setRelatedFunctions] = useState<{ id: string; name: string }[]>([]);
  const [batchTargets, setBatchTargets] = useState<string[]>([]);
  const [batchSaving, setBatchSaving] = useState(false);
  const [presetOperation, setPresetOperation] = useState<
    'create' | 'read' | 'update' | 'delete' | 'custom'
  >('custom');

  const sourceMeta: Record<string, { label: string; color: string }> = {
    custom_metadata: { label: '自定义元数据', color: 'blue' },
    config_file_override: { label: '配置文件覆盖', color: 'purple' },
    openapi_x_ui: { label: 'OpenAPI x-ui', color: 'green' },
    none: { label: '未配置', color: 'default' },
  };
  const sourceDisplay = sourceMeta[uiSource] || { label: uiSource || '未知', color: 'default' };

  // 加载 UI 配置
  const loadUIConfig = async () => {
    if (!functionId) return;

    setLoading(true);
    try {
      const res = await fetchFunctionUISchemaDocument(functionId);
      const config = {
        schema: res?.schema,
        layout: res?.layout,
        components: res?.components,
      };
      if (!config.schema && jsonSchema) {
        config.schema = buildUISchemaFromJSONSchema(jsonSchema);
        setAutoGenerated(true);
      } else {
        setAutoGenerated(false);
      }
      setUiConfig(config);
      setOriginalSchema(config.schema);
      setIsDirty(false);

      const custom = !!res?.custom;
      const hasDefault =
        typeof res?.hasDefault === 'boolean' ? res.hasDefault : !!config.schema && !custom;
      setUseCustomUI(custom);
      setHasDefaultUI(hasDefault);
      setUISource(
        res?.uiSource || (custom ? 'custom_metadata' : hasDefault ? 'openapi_x_ui' : 'none'),
      );
      setUISourceDetail(res?.uiSourceDetail || '');
      setUpdatedAt(res?.updatedAt || '');
    } catch (e: any) {
      if (e?.response?.status === 404) {
        const generated = jsonSchema ? buildUISchemaFromJSONSchema(jsonSchema) : undefined;
        setUiConfig(generated ? { schema: generated } : {});
        setOriginalSchema(undefined);
        setUseCustomUI(false);
        setHasDefaultUI(!!generated);
        setUISource('none');
        setUISourceDetail('');
        setUpdatedAt('');
        setIsDirty(false);
        setAutoGenerated(!!generated);
      } else {
        message.error(e?.message || '加载 UI 配置失败');
      }
    } finally {
      setLoading(false);
    }
  };

  const loadUIHistory = async () => {
    if (!functionId) return;
    setHistoryLoading(true);
    try {
      const res = await fetchFunctionUiHistory(functionId);
      const items = Array.isArray(res?.items) ? res.items : [];
      setHistoryItems(items);
      setRollbackVersion(items[0]?.version);
    } catch {
      setHistoryItems([]);
      setRollbackVersion(undefined);
    } finally {
      setHistoryLoading(false);
    }
  };

  useEffect(() => {
    loadUIConfig();
    loadUIHistory();
  }, [functionId]);

  useEffect(() => {
    const entityKey = String(descriptor?.entity || '')
      .trim()
      .toLowerCase();
    if (!entityKey) {
      setRelatedFunctions([]);
      setBatchTargets([]);
      return;
    }
    listDescriptors()
      .then((res) => {
        const items = Array.isArray(res) ? res : [];
        const same = items
          .filter((it: any) => {
            const e = String(it?.entity || '')
              .trim()
              .toLowerCase();
            return it?.id && e && e === entityKey && it.id !== functionId;
          })
          .map((it: any) => ({
            id: it.id,
            name: it?.displayName?.zh || it?.displayName?.en || it.id,
          }));
        setRelatedFunctions(same);
        setBatchTargets((prev) => prev.filter((id) => same.some((x) => x.id === id)));
      })
      .catch(() => {
        setRelatedFunctions([]);
      });
  }, [descriptor?.entity, functionId]);

  useEffect(() => {
    const op = String(descriptor?.operation || '')
      .trim()
      .toLowerCase();
    if (op === 'create' || op === 'read' || op === 'update' || op === 'delete') {
      setPresetOperation(op);
    } else {
      setPresetOperation('custom');
    }
  }, [descriptor?.operation]);

  // 保存 UI 配置
  const handleSave = async (newUISchema: any) => {
    if (!onSave) {
      message.warning('未配置保存回调');
      return;
    }
    const validation = validateUiSchema(newUISchema);
    if (!validation.ok) {
      message.error(validation.error || 'UI Schema 校验失败');
      return;
    }

    setSaving(true);
    try {
      await onSave({
        schema: newUISchema,
        layout: uiConfig.layout,
        components: uiConfig.components,
      });
      message.success('UI 配置保存成功');
      await loadUIConfig(); // 重新加载
    } catch (e: any) {
      message.error(e?.message || '保存失败');
    } finally {
      setSaving(false);
    }
  };

  const applyCrudPreset = () => {
    const schemaProps = jsonSchema?.properties || {};
    const fieldKeys = Object.keys(schemaProps);
    const required = new Set(jsonSchema?.required || []);
    const idLike = (k: string) => {
      const lower = k.toLowerCase();
      return lower === 'id' || lower.endsWith('_id') || lower.endsWith('id');
    };
    const current = uiConfig.schema && typeof uiConfig.schema === 'object' ? uiConfig.schema : {};
    const next: any = {
      ...current,
      fields: { ...(current.fields || {}) },
      'ui:layout': current['ui:layout'] || { type: 'grid', cols: 2 },
    };
    const ordered = [...fieldKeys].sort((a, b) => {
      const aw = required.has(a) ? 0 : 1;
      const bw = required.has(b) ? 0 : 1;
      if (aw !== bw) return aw - bw;
      return a.localeCompare(b);
    });
    next['ui:order'] = ordered;

    ordered.forEach((key) => {
      const prev = next.fields[key] || {};
      const updated = { ...prev };
      if (!updated.label && schemaProps[key]?.title) {
        updated.label = schemaProps[key].title;
      }
      if (presetOperation === 'read') {
        updated.disabled = true;
      } else {
        if (Object.prototype.hasOwnProperty.call(updated, 'disabled')) {
          delete updated.disabled;
        }
      }
      if (presetOperation === 'create' && idLike(key) && !required.has(key)) {
        updated.disabled = true;
      }
      if (presetOperation === 'update' && idLike(key)) {
        updated.disabled = true;
      }
      if (presetOperation === 'delete') {
        updated.disabled = !idLike(key);
      }
      next.fields[key] = updated;
    });

    setUiConfig((prev) => ({ ...prev, schema: next }));
    setIsDirty(true);
    message.success(`已应用 ${presetOperation.toUpperCase()} 预设`);
  };

  const handleBatchApply = async () => {
    if (!batchTargets.length) {
      message.warning('请先选择目标函数');
      return;
    }
    const payload = {
      schema: uiConfig.schema || {},
      layout: uiConfig.layout,
      components: uiConfig.components,
    };
    setBatchSaving(true);
    try {
      const results = await Promise.allSettled(
        batchTargets.map((targetId) => saveFunctionUiSchema(targetId, payload)),
      );
      const ok = results.filter((r) => r.status === 'fulfilled').length;
      const fail = results.length - ok;
      if (fail === 0) {
        message.success(`已同步 UI 到 ${ok} 个函数`);
      } else {
        message.warning(`同步完成：成功 ${ok}，失败 ${fail}`);
      }
      await loadUIHistory();
    } finally {
      setBatchSaving(false);
    }
  };

  // 切换自定义 UI 开关
  const handleToggleCustomUI = async (checked: boolean) => {
    if (!onSave) {
      message.warning('未配置保存回调');
      return;
    }

    setSaving(true);
    try {
      if (checked) {
        // 启用自定义 UI - 基于当前可见 schema 初始化，避免编辑器空白
        const initialSchema =
          uiConfig.schema && typeof uiConfig.schema === 'object'
            ? uiConfig.schema
            : { type: 'object', properties: {} };
        await onSave({
          schema: initialSchema,
          layout: uiConfig.layout,
          components: uiConfig.components,
        });
        setUseCustomUI(true);
      } else {
        // 禁用自定义 UI - 后端识别该标记后清理 metadata.ui
        await onSave({
          schema: { __clear_custom_ui: true },
          layout: uiConfig.layout,
          components: uiConfig.components,
        });
        setUseCustomUI(false);
      }
      await loadUIConfig();
      message.success(checked ? '已启用自定义 UI' : '已恢复默认 UI');
    } catch (e: any) {
      message.error(e?.message || '操作失败');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <Card>
        <div style={{ textAlign: 'center', padding: 40 }}>
          <Spin />
          <div style={{ marginTop: 12, color: 'rgba(0,0,0,0.45)' }}>加载 UI 配置...</div>
        </div>
      </Card>
    );
  }

  return (
    <Card
      title="UI 配置管理"
      extra={
        <Space>
          <Tag color={useCustomUI ? 'blue' : hasDefaultUI ? 'green' : 'default'}>
            {useCustomUI ? '当前: 自定义' : hasDefaultUI ? '当前: 默认' : '当前: 未配置'}
          </Tag>
          <Tag>来源: {sourceDisplay.label}</Tag>
          <Tag color={sourceDisplay.color}>source={uiSource}</Tag>
          <Button icon={<ReloadOutlined />} onClick={loadUIConfig} loading={loading}>
            刷新
          </Button>
          <Select
            size="small"
            style={{ minWidth: 220 }}
            placeholder="选择历史版本"
            loading={historyLoading}
            value={rollbackVersion}
            onChange={setRollbackVersion}
            options={historyItems.map((it) => ({
              label: `v${it.version} ${
                it.createdAt ? new Date(it.createdAt).toLocaleString('zh-CN') : ''
              }`,
              value: it.version,
            }))}
          />
          <Popconfirm
            title="确认回滚 UI 配置？"
            description={rollbackVersion ? `将回滚到版本 v${rollbackVersion}` : '请选择版本'}
            onConfirm={async () => {
              if (!rollbackVersion) return;
              try {
                setSaving(true);
                await rollbackFunctionUiSchema(functionId, rollbackVersion);
                message.success(`已回滚到版本 v${rollbackVersion}`);
                await loadUIConfig();
                await loadUIHistory();
              } catch (e: any) {
                message.error(e?.message || '回滚失败');
              } finally {
                setSaving(false);
              }
            }}
            okButtonProps={{ disabled: !rollbackVersion }}
          >
            <Button size="small" disabled={!rollbackVersion} loading={saving}>
              回滚
            </Button>
          </Popconfirm>
          {featureFlags.formilyDesigner && (
            <Button
              type="primary"
              onClick={() =>
                history.push(`/system/functions/${encodeURIComponent(functionId)}/ui-designer`)
              }
            >
              打开函数表单设计器
            </Button>
          )}
          {(hasDefaultUI || useCustomUI) && (
            <Space>
              <span>自定义 UI:</span>
              <Switch
                checked={useCustomUI}
                onChange={handleToggleCustomUI}
                loading={saving}
                checkedChildren="启用"
                unCheckedChildren="禁用"
              />
            </Space>
          )}
        </Space>
      }
    >
      <Alert
        message="这里是函数表单配置，不是页面编排"
        description="当前区域只处理单个函数的表单预览和字段展示。若你想把多个函数组织成一个完整操作页面，请返回并进入页面工作台。另：UI 历史、回滚和部分来源跟踪仍包含后端占位实现。"
        type="warning"
        showIcon
        style={{ marginBottom: 16 }}
      />
      {!hasDefaultUI && !uiConfig.schema ? (
        <Empty description="该函数没有配置 UI Schema" />
      ) : featureFlags.formilyDesigner ? (
        <>
          {(descriptor?.entity || descriptor?.operation) && (
            <Card size="small" style={{ marginBottom: 16 }} title="实体化 UI 优化">
              <Row gutter={12}>
                <Col span={24}>
                  <Space wrap>
                    <Tag color="blue">Entity: {String(descriptor?.entity || '-')}</Tag>
                    <Tag color="purple">Operation: {String(descriptor?.operation || 'custom')}</Tag>
                  </Space>
                </Col>
                <Col span={24}>
                  <Space wrap style={{ marginTop: 8 }}>
                    <Select
                      size="small"
                      value={presetOperation}
                      style={{ width: 140 }}
                      onChange={(v) => setPresetOperation(v)}
                      options={[
                        { label: 'Create', value: 'create' },
                        { label: 'Read', value: 'read' },
                        { label: 'Update', value: 'update' },
                        { label: 'Delete', value: 'delete' },
                        { label: 'Custom', value: 'custom' },
                      ]}
                    />
                    <Button size="small" onClick={applyCrudPreset}>
                      应用 CRUD 预设
                    </Button>
                    <Button size="small" onClick={() => handleSave(uiConfig.schema)}>
                      保存到当前函数
                    </Button>
                    <Select
                      size="small"
                      mode="multiple"
                      maxTagCount={2}
                      style={{ minWidth: 320 }}
                      placeholder="选择同实体函数进行批量同步"
                      value={batchTargets}
                      onChange={setBatchTargets}
                      options={relatedFunctions.map((f) => ({ label: f.name, value: f.id }))}
                    />
                    <Button
                      size="small"
                      type="primary"
                      loading={batchSaving}
                      onClick={handleBatchApply}
                    >
                      批量同步 UI
                    </Button>
                  </Space>
                </Col>
                {relatedFunctions.length === 0 && (
                  <Col span={24} style={{ marginTop: 8 }}>
                    <Text type="secondary">当前实体暂无其他函数可同步。</Text>
                  </Col>
                )}
              </Row>
            </Card>
          )}
          <Alert
            message="UI 预览"
            description={
              useCustomUI
                ? '当前使用自定义 UI 配置'
                : hasDefaultUI
                ? '当前使用默认 UI 配置（来自 OpenAPI x-ui 扩展）'
                : '当前无 UI 配置'
            }
            type={useCustomUI ? 'success' : 'info'}
            showIcon
            style={{ marginBottom: 16 }}
          />
          {autoGenerated && (
            <Alert
              message="已自动生成默认 UI"
              description="当前函数无已配置 UI，系统根据 JSON Schema 生成了默认表单。可直接保存为自定义 UI。"
              type="warning"
              showIcon
              action={
                <Button size="small" type="primary" onClick={() => handleSave(uiConfig.schema)}>
                  保存默认 UI
                </Button>
              }
              style={{ marginBottom: 16 }}
            />
          )}
          {uiSourceDetail && (
            <Alert
              message="UI 来源详情"
              description={uiSourceDetail}
              type="info"
              showIcon
              style={{ marginBottom: 16 }}
            />
          )}
          {updatedAt && (
            <Alert
              message="最近更新时间"
              description={new Date(updatedAt).toLocaleString('zh-CN')}
              type="success"
              showIcon
              style={{ marginBottom: 16 }}
            />
          )}

          <SchemaRenderer
            schema={uiConfig.schema}
            readOnly={false}
            context={{
              gameId:
                typeof window !== 'undefined'
                  ? localStorage.getItem('game_id') || undefined
                  : undefined,
              env:
                typeof window !== 'undefined'
                  ? localStorage.getItem('env') || undefined
                  : undefined,
              functionId,
              permissions: String((initialState as any)?.currentUser?.access || '')
                .split(',')
                .filter(Boolean),
            }}
            scope={{
              hasPerm: (perm: string) =>
                String((initialState as any)?.currentUser?.access || '')
                  .split(',')
                  .filter(Boolean)
                  .includes(perm),
              fetchOptions,
            }}
          />
        </>
      ) : (
        <>
          {(descriptor?.entity || descriptor?.operation) && (
            <Card size="small" style={{ marginBottom: 16 }} title="实体化 UI 优化">
              <Row gutter={12}>
                <Col span={24}>
                  <Space wrap>
                    <Tag color="blue">Entity: {String(descriptor?.entity || '-')}</Tag>
                    <Tag color="purple">Operation: {String(descriptor?.operation || 'custom')}</Tag>
                  </Space>
                </Col>
                <Col span={24}>
                  <Space wrap style={{ marginTop: 8 }}>
                    <Select
                      size="small"
                      value={presetOperation}
                      style={{ width: 140 }}
                      onChange={(v) => setPresetOperation(v)}
                      options={[
                        { label: 'Create', value: 'create' },
                        { label: 'Read', value: 'read' },
                        { label: 'Update', value: 'update' },
                        { label: 'Delete', value: 'delete' },
                        { label: 'Custom', value: 'custom' },
                      ]}
                    />
                    <Button size="small" onClick={applyCrudPreset}>
                      应用 CRUD 预设
                    </Button>
                    <Button size="small" onClick={() => handleSave(uiConfig.schema)}>
                      保存到当前函数
                    </Button>
                    <Select
                      size="small"
                      mode="multiple"
                      maxTagCount={2}
                      style={{ minWidth: 320 }}
                      placeholder="选择同实体函数进行批量同步"
                      value={batchTargets}
                      onChange={setBatchTargets}
                      options={relatedFunctions.map((f) => ({ label: f.name, value: f.id }))}
                    />
                    <Button
                      size="small"
                      type="primary"
                      loading={batchSaving}
                      onClick={handleBatchApply}
                    >
                      批量同步 UI
                    </Button>
                  </Space>
                </Col>
                {relatedFunctions.length === 0 && (
                  <Col span={24} style={{ marginTop: 8 }}>
                    <Text type="secondary">当前实体暂无其他函数可同步。</Text>
                  </Col>
                )}
              </Row>
            </Card>
          )}
          <Alert
            message="UI 预览（Legacy）"
            description="当前使用旧版 UI Schema 预览与编辑"
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
          />
          {autoGenerated && (
            <Alert
              message="已自动生成默认 UI"
              description="当前函数无已配置 UI，系统根据 JSON Schema 生成了默认表单。可直接保存为自定义 UI。"
              type="warning"
              showIcon
              action={
                <Button size="small" type="primary" onClick={() => handleSave(uiConfig.schema)}>
                  保存默认 UI
                </Button>
              }
              style={{ marginBottom: 16 }}
            />
          )}

          {jsonSchema ? (
            <FunctionFormRenderer
              schema={jsonSchema}
              uiSchema={uiConfig.schema}
              compact
              submitText="预览提交"
              showReset={false}
            />
          ) : (
            <Alert
              message="无法预览"
              description="缺少函数的 JSON Schema，无法渲染表单预览"
              type="warning"
              showIcon
            />
          )}

          <Divider />

          {!useCustomUI && hasDefaultUI ? (
            <Alert
              message="启用自定义编辑"
              description="请先启用自定义 UI 开关，才能编辑 UI 配置"
              type="warning"
              showIcon
              action={
                <Button type="primary" size="small" onClick={() => handleToggleCustomUI(true)}>
                  启用自定义 UI
                </Button>
              }
            />
          ) : (
            <>
              {isDirty && (
                <Alert
                  message="有未保存修改"
                  description="请点击“保存更改”提交，或“重置更改/取消”放弃本次编辑。"
                  type="warning"
                  showIcon
                  style={{ marginBottom: 16 }}
                />
              )}
              <UISchemaEditor
                value={uiConfig.schema}
                jsonSchema={jsonSchema}
                onChange={(newSchema) => {
                  const changed =
                    JSON.stringify(newSchema ?? null) !== JSON.stringify(originalSchema ?? null);
                  setUiConfig((prev) => ({
                    ...prev,
                    schema: newSchema,
                  }));
                  setIsDirty(changed);
                }}
              />

              <Divider />

              <Space>
                <Button
                  type="primary"
                  onClick={() => handleSave(uiConfig.schema)}
                  loading={saving}
                  disabled={!isDirty}
                >
                  保存更改
                </Button>
                <Button
                  disabled={!isDirty}
                  onClick={() => {
                    setUiConfig((prev) => ({
                      ...prev,
                      schema: originalSchema,
                    }));
                    setIsDirty(false);
                  }}
                >
                  重置更改
                </Button>
                <Button
                  onClick={() => {
                    loadUIConfig();
                  }}
                >
                  取消
                </Button>
              </Space>
            </>
          )}
        </>
      )}
    </Card>
  );
}
