// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import ApiOutlined from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import BlockOutlined from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/BlockOutlined';
import FileOutlined from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/FileOutlined';
import UserOutlined from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from 'D:/workspaces/wingman/dashboard/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { ApiOutlined, BlockOutlined, FileOutlined, UserOutlined, SettingOutlined };
