// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/agents","name":"Agents","icon":"api","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/workflows","name":"Workflows","icon":"block","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/scripts","name":"Scripts","icon":"file","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/account","name":"Account","icon":"user","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/account","redirect":"/account/center","parentId":"7","id":"8"},"9":{"path":"/account/center","name":"Profile","parentId":"7","id":"9"},"10":{"path":"/settings","name":"Settings","icon":"setting","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/403","layout":false,"id":"11"},"12":{"path":"/404","layout":false,"id":"12"},"13":{"path":"*","redirect":"/404","parentId":"ant-design-pro-layout","id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Agents__index" */'@/pages/Agents/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Workflows__index" */'@/pages/Workflows/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Scripts__index" */'@/pages/Scripts/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Profile__index" */'@/pages/Profile/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__403" */'@/pages/403.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'13': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/workspaces/wingman/dashboard/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/workspaces/wingman/dashboard/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
