-- window 模块单元测试

describe("window 模块", function()
    it("应该能获取前台窗口", function()
        local hwnd = window.getForeground()
        assert.is_not_nil(hwnd)
        assert.is_true(hwnd > 0)
    end)

    it("应该能获取前台窗口标题", function()
        local hwnd = window.getForeground()
        local title = window.getTitle(hwnd)
        assert.is_string(title)
        assert.is_true(#title > 0)
    end)

    it("应该能获取前台窗口边界", function()
        local hwnd = window.getForeground()
        local bounds = window.getBounds(hwnd)
        assert.is_not_nil(bounds)
        assert.is_not_nil(bounds.x)
        assert.is_not_nil(bounds.y)
        assert.is_not_nil(bounds.width)
        assert.is_not_nil(bounds.height)
        assert.is_true(bounds.width > 0)
        assert.is_true(bounds.height > 0)
    end)

    it("应该能判断窗口是否前台", function()
        local hwnd = window.getForeground()
        local isForeground = window.isForeground(hwnd)
        assert.is_true(isForeground)
    end)

    it("应该能查找窗口", function()
        -- 尝试查找资源管理器
        local hwnd = window.find("explorer")
        -- 可能找不到或找到多个
        assert.is_true(hwnd == nil or hwnd > 0)
    end)

    it("应该能查找多个窗口", function()
        local windows = window.findAll("explorer")
        assert.is_not_nil(windows)
        assert.is_true(type(windows) == "table")
    end)

    it("应该能获取窗口列表", function()
        local windows = window.list()
        assert.is_not_nil(windows)
        assert.is_true(type(windows) == "table")
        assert.is_true(#windows > 0)
    end)

    it("应该能获取窗口类名", function()
        local hwnd = window.getForeground()
        local className = window.getClassName(hwnd)
        assert.is_string(className)
    end)

    it("应该能获取窗口进程ID", function()
        local hwnd = window.getForeground()
        local pid = window.getProcessId(hwnd)
        assert.is_not_nil(pid)
        assert.is_true(pid > 0)
    end)

    it("应该能判断窗口是否可见", function()
        local hwnd = window.getForeground()
        local visible = window.isVisible(hwnd)
        assert.is_boolean(visible)
        -- 前台窗口应该是可见的
        assert.is_true(visible)
    end)

    it("应该能判断窗口是否最小化", function()
        local hwnd = window.getForeground()
        local minimized = window.isMinimized(hwnd)
        assert.is_boolean(minimized)
    end)

    it("应该能判断窗口是否最大化", function()
        local hwnd = window.getForeground()
        local maximized = window.isMaximized(hwnd)
        assert.is_boolean(maximized)
    end)

    pending("应该能激活窗口", function()
        local hwnd = window.getForeground()
        window.activate(hwnd)
        util.sleep(100)
        local current = window.getForeground()
        assert.is_equal(hwnd, current)
    end)

    pending("应该能设置窗口边界", function()
        local hwnd = window.getForeground()
        local original = window.getBounds(hwnd)
        window.setBounds(hwnd, 100, 100, 800, 600)
        util.sleep(100)
        local bounds = window.getBounds(hwnd)
        assert.is_equal(100, bounds.x)
        assert.is_equal(100, bounds.y)

        -- 恢复原始大小
        window.setBounds(hwnd, original.x, original.y, original.width, original.height)
    end)

    pending("应该能最小化窗口", function()
        local hwnd = window.getForeground()
        window.minimize(hwnd)
        util.sleep(100)
        assert.is_true(window.isMinimized(hwnd))
        window.restore(hwnd)
    end)

    pending("应该能最大化窗口", function()
        local hwnd = window.getForeground()
        window.maximize(hwnd)
        util.sleep(100)
        assert.is_true(window.isMaximized(hwnd))
        window.restore(hwnd)
    end)

    pending("应该能等待窗口出现", function()
        local hwnd = window.waitFor("notexist", 1000)
        assert.is_nil(hwnd) -- 超时返回 nil
    end)
end)
